name: Run Unit Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Aerospike Server
      run: |
        docker run --network=host --name aerospike -it -p 3000:3000 -v .:/etc/aerospike aerospike/aerospike-server-enterprise:latest
    - name: Start Aerospike Proximus
      run: |
        docker run --network=host -p 5000:5000 -v ./aerospike-proximus.yml:/etc/aerospike-proximus/aerospike-proximus.yml -v ./features.conf:/etc/aerospike-proximus/features.conf aerospike/aerospike-proximus:0.3.1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Replace 'x' with the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py
        pip install -r requirements.txt 

    - name: Run unit tests
      run: |
        python -m pytest -s
      working-directory: tests
